### ISSUE TITLE
Character sets are ignored while getting fonts from Google Fonts

### ISSUE THREAD

**Issue by andreyjamer** [battlesnake/gulp-google-webfonts#11]
Plugin doesn't get fonts with character sets different from basic latin. 
Trying to get font with the options: 

```
Roboto:400,300italic,300,100italic,100,400italic,500,500italic,700italic,700,900,900italic&subset=latin,cyrillic-ext,latin-ext,cyrillic
```

But plugin will return only result for the request:

```
Roboto:400,300italic,300,100italic,100,400italic,500,500italic,700italic,700,900,900italic
```

'subset' argument is lost while encodeURIComponent(param) in function requestCss (well, probably, not lost, but not encoded properly, so Google ignores it). 

The problem disappeared when encodeURIComponent was removed from function. I think it's a little bit dirty hack, but can't see another way to fix it.

P.S. Hope my english is not very hard to understand :)

**Comment by battlesnake** [comment]
I understand you fine :) Since this code takes its input from the developer, we can remove `encodeURIComponent` as the input is trusted - are there any normal use cases where you think that this would break things?  Are there any fonts which wouldn't work if we disabled URI encoding for font names?  We could to partial encoding (e.g. " " ⇒ "+") while leaving "&" and "=" alone.

**Comment by andreyjamer** [comment]
I think  we can remove `encodeURIComponent`. But after it must be explained, how to get fonts properly.
In README.md in example of fonts.list there are two fonts: `Oswald` and `Roboto`. But they are very simple (single word, no spaces), so it's unclear how we cant get `Open Sans` or `Julius Sans One`.
Possible ways:

```
Open Sans:400,300,300italic,400italic
```

or

```
Open+Sans:400,300,300italic,400italic
```

And it's not clear how we can get fonts with different subsets.

So my idea is to use Google Font notation for getting fonts. Google uses encoded strings in the code of `<link >` tag. Example:

```
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400italic,600,600italic&subset=latin,latin-ext,greek,greek-ext,vietnamese,cyrillic-ext,cyrillic' rel='stylesheet' type='text/css'>
```

So we can take request arguments and place it to the fonts.list. Example:

```
Open+Sans:400italic,600,600italic&subset=latin,latin-ext,greek,greek-ext,vietnamese,cyrillic-ext,cyrillic
```

I think it will eliminate possible mistakes, it's quite easy to understand. And there will be no need to use `encodeURIComponent` anymore.

**Comment by battlesnake** [comment]
Sounds good.  My other alternative was an `fstab`-style tab-separated format, but that would break compatability.  I was considering treating any like containing a `TAB` as being in `face<TAB>sizes<TAB>subsets` format, and any other lines as being Google-format (already URI-encoded), so we can permit both formats easily.

Is there any reason why I shouldn't replace the `encodeURIComponent(x)` with `x.replace(/ /g, '+')`, so only spaces are encoded?  This would allow people to type `Open Sans:400,400italic&subset=latin,latin-ext` without having any issues due to the space.  Can you see any way that this approach would create problems?

**Comment by andreyjamer** [comment]
Well, i can't see any problems. If people will be able to write `Opens Sans` with spaces or with +, it will be great. And it wouldn't break gulp task for those, who are already using this plugin.

**Comment by battlesnake** [comment]
Pull the latest from this repository and let me know if it has any issues for you.  If not, I'll `npm publish` it.

**Comment by andreyjamer** [comment]
I've tested. There is a mistake in the case with tab-separated format. If we define font with space instead of + the plugin will fail to get fonts. 
I think this mistake can be fixed by changing line 51 from:

```
return parseTabDelimetedLine(line);
```

to 

```
return parseTabDelimetedLine(line).replace(/ /g, '+');
```

**Comment by battlesnake** [comment]
Done, and published - thanks!
