### ISSUE TITLE
Option to download TTF format

### ISSUE THREAD

**Issue by strarsis** [battlesnake/gulp-google-webfonts#12]
Is it possible to add an option to download the TTF format instead (full font file) 
so I can further process it (custom subsetting, woff2 conversion, etc)?

**Comment by battlesnake** [comment]
Sure, this should just be a case of modifying the CSS `template` in `index.js`.  Please could you try that and test it - if it works, send a pull request and I'll merge it!

**Comment by strarsis** [comment]
The full TTFs are available in this repository: https://github.com/google/fonts

Google Fonts API will only deliver optimized/subsetted TTFs, not the full ones.
Does it still make sense to let this plugin download the full TTF instead a TTF from Google Fonts API?

**Comment by battlesnake** [comment]
I'm considering adding some abstraction to the plugin so that it can source fonts from other places besides WebFonts (or creating a new plugin).  I think that such a task would be better for NPM though (I already use NPM for FontAwesome, jQuery, Angular), and then a gulp task which processes all ttf/woff files below the node_modules folder and in some project-specific assets/fonts folder

**Comment by battlesnake** [comment]
Perhaps a new, more generalised plugin would be better for that.  It could handle other font sources also (github, material, font-awesome, npm, bower, etc).

**Comment by michaelmior** [comment]
@strarsis Perhaps this isn't exactly what you want (I haven't inspected the resulting TTF) but there's now a `format` option that will allow you to get the ttf version.
