### ISSUE TITLE
Error: Invalid output folder

### ISSUE THREAD

**Issue by jdnichollsc** [battlesnake/gulp-google-webfonts#19]
Hi man,

See an issue with the plugin: http://screencast.com/t/yEkrahyCM0

And the paths are:

```
var paths = {
    fonts: 'app/fonts.list',
    fontOptions: {
        fontsDir: 'fonts/',
        cssDir: 'css/',
        cssFilename: 'fonts.css'
    },
    destFonts: './www/'
};
```

Regards, Nicholls

**Comment by battlesnake** [comment]
The error message seems quite self-explanatory although I'm not sure why you couldn't just paste it here instead of linking to it...

Create the output folder first

**Comment by jdnichollsc** [comment]
The output folder exist :)

**Comment by battlesnake** [comment]
For lack of any other useful debugging information, I'd suggest reading the stack trace carefully, the font downloader doesn't seem to appear in it.

If you could paste the actual error message instead of linking to an incomplete screenshot, and maybe provide some information regarding your environment and the version of the plugin that you're using, that might help.
