### ISSUE TITLE
build fonts.list for gulp-google-webfonts

### ISSUE THREAD

**Issue by colorwebdesigner** [battlesnake/gulp-google-webfonts#44]
Hi
I've made function to build `fonts.list`. You need just copy one of this format at Google Fonts and paste into variable:

`<link href="https://fonts.googleapis.com/css?family=Lobster&amp;subset=cyrillic" rel="stylesheet"> ` 
or 
`@import url('https://fonts.googleapis.com/css?family=Lobster&subset=cyrillic');`

It is on my gists:
https://gist.github.com/colorwebdesigner/c28b81a85a22663433aa67583f9c318b

**Comment by battlesnake** [comment]
Thanks.  Feel free to add a PR with that link added to the README.  The `fonts.list` format is intended to be minimal and intuitive such that if I know the name of a font then I can just add it to the list, instead of having to go to Google WebFonts.

For all other cases, your script/plugin looks quite useful.
